[project]
name = "readdy"
version = "3.0.0"
description = "ReaDDy is a particle-based reaction-diffusion simulator for biological mesoscale systems."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [{ name = "Eric Arkfeld", email = "e.c.arkfeld@gmail.com" }]
keywords = ["py-build-cmake", "pybind11", "reaction-diffusion", "simulation"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
]
dependencies = []

[project.optional-dependencies]
test = ["pytest>=7.2.0,<9"]

[build-system]
requires = [
    "py-build-cmake>=0.5.0",
    "pybind11-stubgen~=2.5.1",
    "conan>=2.0",
    "numpy>=1.21"
]
build-backend = "py_build_cmake.build"

[tool.py-build-cmake.module]
name = "readdy"
directory = "wrappers/python/src/python"

[tool.py-build-cmake.stubgen]

[tool.py-build-cmake.sdist]
include = [
    "conanfile.py",
    "CMakeLists.txt",
    "cmake",
    "readdy",
    "LICENSE",
    "README.md"
]

[tool.py-build-cmake.cmake]
minimum_version = "3.25"
build_path = "build"
build_type = "Release"
cmake-args = [
    "-DREADDY_BUILD_PYTHON_WRAPPER=ON",
    "-DREADDY_CREATE_TEST_TARGET=OFF",
    "-DREADDY_INSTALL_UNIT_TEST_EXECUTABLE=OFF",
    "-DREADDY_LOG_CMAKE_CONFIGURATION=ON",
    "-DREADDY_GENERATE_DOCUMENTATION_TARGET=OFF",
    "-DREADDY_BUILD_MPI_KERNEL=OFF",
    "-DREADDY_BUILD_SHARED_COMBINED=OFF",
    "-DCMAKE_CXX_FLAGS_RELEASE=-O3",
    "-DCMAKE_C_FLAGS_RELEASE=-O3",
    "-DPYTHON_EXECUTABLE=${python_executable}"
]

[tool.py-build-cmake.mac.cmake]
generator = "Ninja Multi-Config"

[tool.py-build-cmake.linux.cmake]
generator = "Ninja Multi-Config"

[tool.cibuildwheel]
archs = ["auto64"]
skip = "pp37-*"
build-frontend = "build"
environment = { PY_BUILD_CMAKE_VERBOSE = "1" }
test-extras = ["test"]
test-command = "pytest {project}/test"

[tool.cibuildwheel.macos]
archs = ["arm64", "x86_64", "universal2"]
before-build = [
    "pip install cmake 'conan>=2,<3' ninja",
    "conan profile detect -f",
    "rm -rf {package}/build",
    "python {package}/tools/ci/pre-build-macos.py"
]

[tool.cibuildwheel.windows]
archs = ["AMD64", "x86", "ARM64"]
before-build = [
    "python -m pip install cmake \"conan>=2,<3\" ninja",
    "conan profile detect -f",
    "(if exist {package}\\build (rmdir /s /q {package}\\build))",
    "python {package}\\tools\\ci\\pre-build-windows.py"
]

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = ["test"]
