[project]
name = "readdy"
version = "3.0.0"
description = "ReaDDy is a particle-based reaction-diffusion simulator for biological mesoscale systems."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [{ name = "Eric Arkfeld", email = "e.c.arkfeld@gmail.com" }]
keywords = ["py-build-cmake", "pybind11", "reaction-diffusion", "simulation"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
]
dependencies = [
    "blosc>=1.11.0",
#    "hdf5>=1.14.3",
    "h5py>=3.13.0",
#    "numpy>=1.21",
    "tqdm>=4.64.0",
]

[project.optional-dependencies]
test = ["pytest>=7.2.0,<9"]

[build-system]
requires = [
    "py-build-cmake>=0.4.2",
    "pybind11-stubgen~=2.5.1",
    "cmake>=3.16",
    "conan>=2.0",
    "ninja",
    "blosc>=1.11.0",
    "h5py>=3.13.0",
#    "hdf5>=1.14.3",
#    "numpy>=1.21",
]
build-backend = "py_build_cmake.build"

[tool.py-build-cmake.module]
name = "readdy"
directory = "wrappers/python/src/python"

[tool.py-build-cmake.stubgen]

[tool.py-build-cmake.sdist]
include = [
    "conanfile.py",
    "CMakeLists.txt",
    "cmake",
    "readdy",
    "LICENSE",
    "README.md"
]

[tool.py-build-cmake.cmake]
minimum_version = "3.25"
build_path = "build"
build_type = "Debug"

[tool.py-build-cmake.cmake.options]
READDY_BUILD_PYTHON_WRAPPER = true
READDY_CREATE_TEST_TARGET = true
READDY_INSTALL_UNIT_TEST_EXECUTABLE = false
READDY_LOG_CMAKE_CONFIGURATION = true
READDY_GENERATE_DOCUMENTATION_TARGET = false
READDY_BUILD_MPI_KERNEL = false
CMAKE_CXX_FLAGS_RELEASE = "-O3"
CMAKE_C_FLAGS_RELEASE = "-O3"
CMAKE_PREFIX_PATH = "build/generators"

[tool.py-build-cmake.mac.cmake]
generator = "Ninja Multi-Config"

[tool.py-build-cmake.linux.cmake]
generator = "Ninja Multi-Config"

[tool.cibuildwheel]
archs = ["auto64"]
skip = "pp37-*"
build-frontend = "build"
environment = { PY_BUILD_CMAKE_VERBOSE = "1" }
test-extras = ["test"]
test-command = "pytest {project}/test"

[tool.cibuildwheel.macos]
archs = ["arm64", "x86_64", "universal2"]
before-build = [
#    "pip install cmake 'conan>=2,<3' ninja",
    "pip install cmake 'conan>=2,<3' ninja blosc h5py",
    "conan profile detect -f",
    "rm -rf {package}/build",
    "python {package}/tools/ci/pre-build-macos.py"
]

[tool.cibuildwheel.windows]
archs = ["AMD64", "x86", "ARM64"]
before-build = [
#    "python -m pip install cmake \"conan>=2,<3\" ninja",
    "pip install cmake 'conan>=2,<3' ninja blosc h5py",
    "conan profile detect -f",
    "(if exist {package}\\build (rmdir /s /q {package}\\build))",
    "python {package}\\tools\\ci\\pre-build-windows.py"
]

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = ["test"]